# Generated by Django 2.1.2 on 2018-11-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20181115_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articla',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='articla',
            name='title',
            field=models.TextField(help_text='articla title', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='details',
            field=models.TextField(help_text='author details'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.ForeignKey(help_text='authon name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(help_text='catagory name', max_length=100),
        ),
    ]
