# Generated by Django 2.1.2 on 2018-11-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20181115_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articla',
            options={},
        ),
    ]
