# Generated by Django 2.1.2 on 2018-11-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20181115_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='articla',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
